# name of the workflow.
# this is optional.
name: Build Container & Upload

# events that will trigger this workflow.
# here, we only have "pull_request", so the workflow will run
# whenever we create a pull request.
# other examples: [push] and [pull_request, push]
on:
  # pull_request:

  push:
    branches:
      - master
      - actionRework

# each workflow must have at least one job.
# jobs run in parallel by default (we can change that).
# each job groups together a series of steps to accomplish a purpose.
jobs:
  deploy:
    runs-on: ubuntu
    # if: ${{ github.ref == 'refs/heads/master' || github.event.pull_request.merged == true }} # Runs if it's a push to 'main' or a merged PR to 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

        # log into docker hub
      # - name: Login to Dockerhub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }} # Using secret for Docker username
      #     password: ${{ secrets.DOCKER_PASSWORD }} # Using secret for Docker password
      #   id: docker-login

      # Login to Forgejo registry
      # - name: Login to Forgejo Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: forge.ucalgarybaja.ca
      #     username: ${{ secrets.FORGEJO_REGISTRY_USER }}
      #     password: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
      #   id: forgejo-login

      - name: List Forgejo runner envs
        run: printenv | sort

      # - name: Build & Publish for Forgejo CR (latest)
      #   uses: https://data.forgejo.org/forgejo/forgejo-build-publish/build@v5.5.1
      #   with:
      #     forgejo: "${{ env.GITHUB_SERVER_URL }}"
      #     owner: "${{ env.GITHUB_REPOSITORY_OWNER }}"
      #     repository: "${{ steps.repository.outputs.value }}"
      #     doer: "ucalgary-baja-releases"
      #     release-version: "latest"
      #     sha: "${{ github.sha }}"
      #     token: "${{ secrets.FORGEJO_REGISTRY_TOKEN }}"
      #     platforms: linux/amd64
      #     dockerfile: dockerfile

      # - name: Build & Publish for Forgejo CR (SHA)
      #   uses: https://data.forgejo.org/forgejo/forgejo-build-publish/build@v5.5.1
      #   with:
      #     forgejo: "${{ env.GITHUB_SERVER_URL }}"
      #     owner: "${{ env.GITHUB_REPOSITORY_OWNER }}"
      #     repository: "${{ steps.repository.outputs.value }}"
      #     doer: "ucalgary-baja-releases"
      #     release-version: "${{ github.sha }}"
      #     sha: "${{ github.sha }}"
      #     token: "${{ secrets.FORGEJO_REGISTRY_TOKEN }}"
      #     platforms: linux/amd64
      #     dockerfile: dockerfile

      # - name: Publish To Forgejo Container Registry
      #   uses: https://data.forgejo.org/forgejo/forgejo-build-publish/publish@v5.5.1
      #   with:
      #     to-owner: "forgejo-experimental"
      #     to-doer: "ucalgarybaja-releaes-team"
      #     to-token: "${{ secrets.FORGEJO_REGISTRY_TOKEN }}"

      # - name: build container image # build the container
      #   run: docker compose build --no-cache
      #   id: docker-build

      # - name: Upload to Dockerhub
      #   run: docker push darkicewolf50/ucalg-baja-cloud:latest
      #   if: ${{ steps.docker-login.outcome == 'success' && steps.docker-build.outcome == 'success' }}

      # - name: Upload to Dockerhub with Git SHA tag
      #   run: |
      #     docker tag darkicewolf50/ucalg-baja-cloud:latest darkicewolf50/darkicewolf50cloud:${{ github.sha }}
      #     docker push darkicewolf50/darkicewolf50cloud:${{ github.sha }}
      #   if: ${{ steps.docker-login.outcome == 'success' && steps.docker-build.outcome == 'success' }}

      # - name: Upload to Forgejo with Git SHA tag
      #   run: |
      #     docker tag darkicewolf50/ucalg-baja-cloud:latest forge.ucalgarybaja.ca/ucalgary-baja/ucalg-baja-cloud:${{ github.sha }}
      #     docker push forge.ucalgarybaja.ca/ucalgary-baja/ucalg-baja-cloud:${{ github.sha }}
      #   if: ${{ steps.forgejo-login.outcome == 'success' && steps.docker-build.outcome == 'success' }}

      # - name: Upload to Forgejo
      #   run: |
      #     docker tag darkicewolf50/ucalg-baja-cloud:latest forge.ucalgarybaja.ca/ucalgary-baja/ucalg-baja-cloud:latest
      #     docker push forge.ucalgarybaja.ca/ucalgary-baja/ucalg-baja-cloud:latest
      #   if: ${{ steps.forgejo-login.outcome == 'success' && steps.docker-build.outcome == 'success' }}
