[registries.darkicewolf50-forge]
index = "sparse+https://forge.ucalgarybaja.ca/api/packages/cnidariaware/cargo/" # Sparse index
# index = "https://forge.ucalgarybaja.ca/cnidariaware/_cargo-index.git" # Git

[net]
git-fetch-with-cli = true